name: Deploy Bicep Files

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Verify Azure CLI Login
      run: |
        az account show

    - name: Deploy Bicep file
      run: |
        az deployment group create --resource-group demo --template-file Azure_Telemetry_Template.bicep